# Generated by Django 4.0.5 on 2024-06-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('seniority', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('ranking', models.IntegerField()),
                ('selected_status', models.BooleanField(default=False)),
                ('raw_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('number_of_employees', models.IntegerField()),
                ('raw_json', models.JSONField()),
            ],
        ),
    ]
